### ISSUE TITLE
GetGitRevisionDescription: git_local_changes() returns false positive when repo. source file touched

### ISSUE THREAD

**Issue by RichardLangFromNZ** [rpavlik/cmake-modules#49]
My project contains a source file detailing software version information, which I `touch` at the start of every build to ensure that it is unconditionally built such that a project build timestamp derived from C `__DATE__`  and  `__TIME__` macros is up to date.

The `git diff-index --quiet HEAD --` command used in the git_local_changes() function results in the repo. being evaluated as dirty once a source file has been touched, and doesn't come right until some other git operation performs an index refresh.

See https://stackoverflow.com/questions/34807971 for a discussion of `git diff-index` behaviour.

Seems to me that using `git diff --quiet HEAD --` instead results in desired behaviour.  Alternately can issue `git update-index --refresh` before the `git diff-index` call.

**Comment by rpavlik** [comment]
Hmm. I'm not sure the best way to do this, especially given that generating/modifying a source file in the source directory (instead of the build directory) is not really recommended with CMake.  Additionally, reproducible builds work makes use of __DATE__ and __TIME__ something that compilers are warning about these days.

If it still sounds like there's an issue here, you're welcome to submit a pull request. Do note however that this module is by far the most popular in this repo, so changes should be made with care :)
